name: build go 1.24

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - go/1.24/**

permissions:
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Lowercase the repo owner for GHCR tag
      - name: Lowercase repo owner
        id: repo
        run: |
          echo "owner=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      # Log in to GHCR
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ steps.repo.outputs.owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image
      - uses: docker/build-push-action@v6
        with:
          context: ./go/1.24
          file: ./go/1.24/Dockerfile
          push: true
          tags: ghcr.io/${{ steps.repo.outputs.owner }}/golang-pterodactyl:go_1.24
